name: footwear_client
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  dropdown_button2: ^2.3.9
  get: ^4.6.6
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  get_storage: ^2.1.1
  otp_text_field_v2: ^1.0.3
  crypto: ^3.0.6
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.4
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  flutter_test:
    sdk: flutter

  # Lints package for better coding practices
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Optionally add assets or fonts if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
